#!/system/bin/sh

if [ -e /system/bin/log ];
then
    LOGI="log -p i -t mountsd --"
    LOGE="log -p e -t mountsd --"
else
    LOGI=echo
    LOGE=echo
fi

DEFAULT_KB="2048KB"
DEFAULT=`/system/xbin/echo $DEFAULT_KB | /system/xbin/sed 's/KB//'`
PROP_KB=`getprop persist.sys.sdcardcachereadsize`
PROP=`/system/xbin/echo $PROP_KB | /system/xbin/sed 's/KB//'`
RECVERSION=`strings /sbin/recovery|/system/xbin/grep Recovery | /system/xbin/head -n 1`
KERNELVERSION=`cat /proc/version |awk {'print $3'}`

if [ -n "$PROP_KB" ];
then
    $LOGI "Defined SD-Card cache read size is $PROP_KB"
    if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]
    then
        /system/xbin/echo $PROP > /sys/devices/virtual/bdi/179\:0/read_ahead_kb
    fi
else
    $LOGI "No SD-Card cache read size defined, using default of $DEFAULT_KB"
    setprop persist.sys.sdcardcachereadsize $DEFAULT_KB
    /system/xbin/echo $DEFAULT > /sys/devices/virtual/bdi/179:0/read_ahead_kb
fi

setprop ro.recver "$RECVERSION"
setprop ro.kernelversion "$KERNELVERSION"

